### ISSUE TITLE
Htmlifier not working, error code given

### ISSUE THREAD

**Issue by Xblader1359** [SheepTester/htmlifier#158]
I don't know why this is happening. When i try to use htmlifier it gives me this:

Unexpected error:
Error: Received HTTP 403 error for https://projects.scratch.mit.edu/0
    at toBlob (https://sheeptester.github.io/htmlifier/index.bundle.min.js:1:414764)
    at async https://sheeptester.github.io/htmlifier/index.bundle.min.js:1:7376892
    at async Htmlifier._createHtml (https://sheeptester.github.io/htmlifier/index.bundle.min.js:1:7376746)
    at async Htmlifier.htmlify (https://sheeptester.github.io/htmlifier/index.bundle.min.js:1:7426098)

please help me

**Comment by SheepTester** [comment]
can you send a screenshot of the options you're using?

**Comment by Xblader1359** [comment]
Sure, here you go. 
![IMG_0590](https://github.com/user-attachments/assets/57e8c7fa-dadb-4443-b822-581fc12f586b)
![IMG_0593](https://github.com/user-attachments/assets/815d253d-40f6-41a8-8959-1a9e4e7f2642)
![IMG_0592](https://github.com/user-attachments/assets/4142926c-cf59-43bb-91c5-82059a95c5bf)
![IMG_0591](https://github.com/user-attachments/assets/d53c9554-d1f0-4791-92bc-a093e6b24254)
![IMG_0589](https://github.com/user-attachments/assets/ac88a4c7-c615-42dc-a813-7656f2fb0c73)

**Comment by SheepTester** [comment]
hmm, I think the error is caused when you have "a project ID on Scratch" selected rather than "selecting a file on your computer", so it tried to get a project with ID 0. Can you make sure you have the "selecting a file on your computer" option selected and try again?

![image](https://github.com/user-attachments/assets/7a5fd525-4070-4171-ab23-a7324b589900)

**Comment by Xblader1359** [comment]
I forgot to mention that this is a recreation of the original with the settings. I got the error while using a url or id, but didn’t with a file. When I tried the file, though, the result didn’t let me edit the project, so is there any way to download a version of a project where I can edit the code and sprites?

**Comment by SheepTester** [comment]
yeah, you won't be able to edit the project when you HTMLify it. the idea is that you'd finish editing your project in Scratch, then htmlify it when you're done

uploading projects by ID doesn't work anymore

**Comment by Xblader1359** [comment]
All good. Is there any other way you know of so that I can download an html file of scratch so I can edit projects on it?

**Comment by SheepTester** [comment]
i don't think so, but why do you need an html file? why not just the scratch editor?

**Comment by Xblader1359** [comment]
I just want to use it offline.

**Comment by jimmyorr** [comment]
It seems to be trying to download url with the format:

https://projects.scratch.mit.edu/12345

...but maybe needs to be in the format:

https://scratch.mit.edu/projects/12345
